version: '3.8'

services:
  bic-nextjs:
    build:
      context: ./bic-nextjs
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: bic-nextjs:latest
    restart: unless-stopped
    # Coolify handles port mapping through its proxy
    # No ports section needed here
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - bic-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {if (r.statusCode !== 200) throw new Error(); process.exit(0)}).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bic-network:
    driver: bridge