version: '3.8'

services:
  bic-nextjs-dev:
    build:
      context: ./bic-nextjs
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    image: bic-nextjs:dev
    container_name: bic-nextjs-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      # Next.js dev server websocket port for hot reload
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true # For Windows/Mac compatibility
      # Add your development environment variables here
    volumes:
      # Mount the entire app directory for hot reload
      - ./bic-nextjs:/app
      # Use anonymous volumes for node_modules to avoid conflicts
      - /app/node_modules
      - /app/.next
    networks:
      - bic-dev-network
    command: pnpm dev

networks:
  bic-dev-network:
    driver: bridge